export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "1",
    flightNumber: "FL-1042",
    origin: "Toronto",
    originCode: "YYZ",
    destination: "Tokyo",
    destinationCode: "NRT",
    departureDate: "Apr 12, 2026",
    departureTime: "10:30",
    arrivalTime: "14:45+1",
    duration: "13h 15m",
    status: "upcoming",
    seat: "12A",
    class: "Economy",
    gate: "D22",
    aircraft: "Boeing 787-9",
    price: "$1,240.00",
  },
  {
    id: "2",
    flightNumber: "FL-0887",
    origin: "Vancouver",
    originCode: "YVR",
    destination: "London",
    destinationCode: "LHR",
    departureDate: "Mar 3, 2026",
    departureTime: "18:00",
    arrivalTime: "09:15+1",
    duration: "9h 15m",
    status: "upcoming",
    seat: "4C",
    class: "Business",
    gate: "B07",
    aircraft: "Airbus A350",
    price: "$3,850.00",
  },
  {
    id: "3",
    flightNumber: "FL-1234",
    origin: "Toronto",
    originCode: "YYZ",
    destination: "Tokyo",
    destinationCode: "NRT",
    departureDate: "Feb 15, 2026",
    departureTime: "11:00",
    arrivalTime: "15:20+1",
    duration: "13h 20m",
    status: "completed",
    seat: "22F",
    class: "Economy",
    aircraft: "Boeing 777-300ER",
    price: "$980.00",
  },
  {
    id: "4",
    flightNumber: "FL-0561",
    origin: "Montreal",
    originCode: "YUL",
    destination: "Paris",
    destinationCode: "CDG",
    departureDate: "Jan 8, 2026",
    departureTime: "21:45",
    arrivalTime: "10:30+1",
    duration: "7h 45m",
    status: "completed",
    seat: "8B",
    class: "Economy",
    aircraft: "Airbus A330",
    price: "$740.00",
  },
  {
    id: "5",
    flightNumber: "FL-0392",
    origin: "Calgary",
    originCode: "YYC",
    destination: "New York",
    destinationCode: "JFK",
    departureDate: "Dec 20, 2025",
    departureTime: "07:15",
    arrivalTime: "14:50",
    duration: "4h 35m",
    status: "cancelled",
    seat: "31D",
    class: "Economy",
    aircraft: "Boeing 737-800",
    price: "$420.00",
  },
]
